### ISSUE TITLE
[Question] Forward proxy-server port

### ISSUE THREAD

**Issue by caiobrentano** [swiftstack/vagrant-swift-all-in-one#57]
Hi friends,

Am I missing something or the proxy-server port is not being forward to allow requests from the host?
Is there any reason for that?

Thanks and congrats for this beautiful swift vagrant box!

**Comment by clayg** [comment]
Oh goodness!  Sorry for the late rely.  The specific ports for the proxy do not need to be "forwarded" because of the private network ip.  Basically you can connect to any port if you use the ip configured for the guest.

I think the README gets into it a *little* bit?

https://github.com/swiftstack/vagrant-swift-all-in-one/blob/master/README.md#ninja-dev-tricks
